- name: Deploy Flask App to Azure Container Instances
  hosts: localhost
  tasks:
    - name: Log in to Azure Container Registry
      azure_rm_containerregistry:
        resource_group: bloggroup
        username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
        password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
        login_server: 3345blog.azurecr.io
        state: present
