---
- name: Deploy to Azure Container Instances
  hosts: all
  become: yes

  tasks:
    - name: Login to Azure Container Registry
      shell: az acr login --name <registry-name> --username "{{ REGISTRY_USERNAME }}" --password "{{ REGISTRY_PASSWORD }}"
      environment:
        REGISTRY_USERNAME: "{{ REGISTRY_USERNAME }}"
        REGISTRY_PASSWORD: "{{ REGISTRY_PASSWORD }}"

    - name: Pull Docker image from Azure Container Registry
      shell: docker pull 3345blog.azurecr.io/blogv2:{{ github.sha }}

    - name: Create Azure Container Instance
      azure_rm_containerinstance:
        resource_group: blogacigroup
        name: blogaci
        image: 3345blog.azurecr.io/blogv2:{{ github.sha }}
        dns_name_label: blogv2
        cpu: 1
        memory_in_gb: 1
        os_type: Linux
        state: present
