name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          build: |
             docker build -t ${{ secrets.DOCKER_NAME }}/blogv1:${{ github.sha }} -f Dockerfile .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/blogv1:${{ github.sha }}
          file: Dockerfile

      - name: Docker Login for ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          # Build Docker images using Docker Compose and tag them
          docker-compose -f docker-compose.yml build

          # Tag the built images correctly
          docker tag blogv1 ${{ secrets.REGISTRY_LOGIN_SERVER }}/blogv1
          docker tag 3345-flask-app ${{ secrets.REGISTRY_LOGIN_SERVER }}/3345-flask-app

          # Push the Docker images to Azure Container Registry
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/blogv1
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/3345-flask-app
